# Generated by Django 4.1.3 on 2022-11-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='YoutubeLink',
        ),
    ]
