# Generated by Django 4.1.2 on 2022-10-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubelink',
            name='video_link',
            field=models.TextField(max_length=5000),
        ),
    ]
