# Generated by Django 4.1.3 on 2022-11-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_media_youtubelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubelink',
            name='video_link',
            field=models.TextField(max_length=255),
        ),
    ]
