# Generated by Django 4.1.3 on 2022-11-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_youtubelink_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='link',
            new_name='lithought_link',
        ),
    ]
