# Generated by Django 4.1.3 on 2022-11-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_link_thought_lithought_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='lithought_link',
            new_name='thought_link',
        ),
    ]
